version: "3.8"
services:
  server:
    image: cleveraf/springsql:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/testdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb

  mysqldb:
    platform: linux/arm64/v8 #needed for linux (linux/x86-64) and macs
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      DATABASE_PORT: 3306
      DATABASE_HOST: docker-mysql
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root